name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Lint (ESLint)
        run: npm run lint:check
        continue-on-error: true

      - name: Type check
        run: npm run lint:types
        continue-on-error: true

      - name: Format check (Prettier)
        run: npm run format:check
        continue-on-error: true

      - name: Package
        run: npm run package

  nix-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Build Nix package
        run: nix build

  arch-build:
    name: Build Arch Linux Package
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel git namcap

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check PKGBUILD with namcap
        # Run namcap to lint the PKGBUILD for common errors
        run: namcap packaging/arch/PKGBUILD

      - name: Build package
        run: |
          # makepkg cannot be run as root, so we create a builder user
          useradd -m builder
          # Give the builder user permissions for the repo
          chown -R builder:builder .
          # Run makepkg as the non-root user
          sudo -u builder makepkg -sf --noconfirm
        working-directory: ./packaging/arch
